"""Self-contained LeRobot dataset v2.1 writer (no `lerobot` dependency).

Writes the exact on-disk format that `lerobot` 0.3.3 (codebase_version v2.1) produces and loads,
verified against a reference dataset generated by lerobot itself. Used to export DOMINO demos to a
LeRobot dataset INLINE during collection, alongside the existing HDF5/mp4 output, WITHOUT importing
`lerobot` into the sim env (which would risk the hand-built aarch64 torch).

Layout (BEHAVIOR-1K style; both this and the default `chunk-` template load with stock lerobot):
    data/task-{TT:04d}/episode_{EE:08d}.parquet
    videos/task-{TT:04d}/{video_key}/episode_{EE:08d}.mp4
    annotations/task-{TT:04d}/episode_{EE:08d}.json
    meta/_parts/task-{TT:04d}.{episodes,episodes_stats}.jsonl + .info.json   (merged later)

Each DOMINO task owns a fixed task_index == episode_chunk; episodes are pre-allocated
episode_index = task_index*chunks_size + local, so parallel per-task jobs never collide and the
merge (envs/utils/merge_lerobot_meta.py) is pure concatenation — no reindexing, no data copy.
"""
import os
import json
import tempfile
import numpy as np
import pyarrow as pa
import pyarrow.parquet as pq

from .images_to_video import images_to_video

CODEBASE_VERSION = "v2.1"
# frame `index` (global, unique) is pre-allocated per task block: index = task_index*INDEX_STRIDE + i
INDEX_STRIDE = 100_000_000

DATA_PATH = "data/task-{episode_chunk:04d}/episode_{episode_index:08d}.parquet"
VIDEO_PATH = "videos/task-{episode_chunk:04d}/{video_key}/episode_{episode_index:08d}.mp4"
ANNOTATION_PATH = "annotations/task-{episode_chunk:04d}/episode_{episode_index:08d}.json"


# --------------------------------------------------------------------------- stats helpers
def _stats_vec(arr):
    """Per-dimension stats for a (n, d) float array → lists of length d."""
    arr = np.asarray(arr, dtype=np.float64)
    return {
        "min": arr.min(0).tolist(),
        "max": arr.max(0).tolist(),
        "mean": arr.mean(0).tolist(),
        "std": arr.std(0).tolist(),
        "count": [int(arr.shape[0])],
    }


def _stats_scalar(arr):
    """Stats for a (n,) array → single-element lists (matches lerobot's shape-[1] features)."""
    a = np.asarray(arr, dtype=np.float64).reshape(-1)
    return {
        "min": [float(a.min())],
        "max": [float(a.max())],
        "mean": [float(a.mean())],
        "std": [float(a.std())],
        "count": [int(a.shape[0])],
    }


def _stats_image(frames):
    """Per-channel stats over normalized [0,1] pixels → shape-[3,1,1] nested lists (lerobot format)."""
    x = np.stack(frames).astype(np.float32) / 255.0  # (n, H, W, 3)
    axes = (0, 1, 2)
    fmt = lambda v: [[[float(c)]] for c in v]
    return {
        "min": fmt(x.min(axes)),
        "max": fmt(x.max(axes)),
        "mean": fmt(x.mean(axes)),
        "std": fmt(x.std(axes)),
        "count": [int(x.shape[0])],
    }


def _hf_type(dtype, shape):
    """HF `datasets` type encoding embedded in the parquet schema metadata."""
    if shape is None or len(shape) == 0 or (len(shape) == 1 and int(shape[0]) == 1):
        return {"dtype": dtype, "_type": "Value"}
    return {"feature": {"dtype": dtype, "_type": "Value"}, "length": int(shape[0]), "_type": "Sequence"}


class LeRobotV21Writer:
    """One instance per (task, collection job). Writes directly into the shared combined dataset's
    per-task folders + per-task meta slices. Call add_frame() per frame, save_episode() per episode,
    close() at the end of the job."""

    def __init__(self, root, task_index, task_name, features, fps, robot_type="aloha-agilex",
                 chunks_size=1000, video_codec="h264"):
        self.root = root
        self.task_index = int(task_index)
        self.task_name = task_name
        self.features = features            # full feature dict incl. video features
        self.fps = float(fps)
        self.robot_type = robot_type
        self.chunks_size = int(chunks_size)
        self.video_codec = video_codec
        self.episode_chunk = self.task_index   # by construction: episode_index // chunks_size == task_index

        # split features into video (-> mp4) and tabular (-> parquet, excludes video)
        self.video_keys = [k for k, v in features.items() if v["dtype"] == "video"]
        self.vector_keys = [k for k, v in features.items()
                            if v["dtype"] not in ("video",) and len(v["shape"]) == 1 and v["shape"][0] > 1]
        # scalar bookkeeping columns lerobot always writes
        self.scalar_int_keys = ["frame_index", "episode_index", "index", "task_index"]
        self.scalar_float_keys = ["timestamp"]

        self._tt = f"task-{self.episode_chunk:04d}"
        for sub in ("data", "videos", "annotations", os.path.join("meta", "_parts")):
            os.makedirs(os.path.join(root, sub), exist_ok=True)
        os.makedirs(os.path.join(root, "data", self._tt), exist_ok=True)
        for vk in self.video_keys:
            os.makedirs(os.path.join(root, "videos", self._tt, vk), exist_ok=True)
        os.makedirs(os.path.join(root, "annotations", self._tt), exist_ok=True)

        # resume support: continue after any episodes already written for this task
        existing = [f for f in os.listdir(os.path.join(root, "data", self._tt)) if f.endswith(".parquet")]
        self._local = len(existing)
        self._frames_so_far = 0  # recount below for a correct global `index` base
        for f in sorted(existing):
            self._frames_so_far += pq.read_metadata(os.path.join(root, "data", self._tt, f)).num_rows

        self._buf = None
        self._reset_buf()
        self._ep_lines = []        # episodes.jsonl slice
        self._stats_lines = []     # episodes_stats.jsonl slice
        self._task_strings = {}    # task_index -> canonical task string (this writer owns one)

    def _reset_buf(self):
        self._buf = {"images": {vk: [] for vk in self.video_keys},
                     "vectors": {k: [] for k in self.vector_keys}}

    # ------------------------------------------------------------------ per-frame
    def add_frame(self, vectors: dict, images: dict):
        """vectors: {feature_name: 1D np.float32 array}; images: {video_key: HxWx3 uint8 array}."""
        for k in self.vector_keys:
            self._buf["vectors"][k].append(np.asarray(vectors[k], dtype=np.float32))
        for vk in self.video_keys:
            self._buf["images"][vk].append(np.asarray(images[vk]))

    # ------------------------------------------------------------------ per-episode
    def save_episode(self, task: str, success: bool, annotation: dict | None = None, extra_ep: dict | None = None):
        n = len(next(iter(self._buf["vectors"].values()))) if self.vector_keys else len(
            self._buf["images"][self.video_keys[0]])
        if n == 0:
            self._reset_buf()
            return None
        ee = self.task_index * self.chunks_size + self._local
        idx_base = self.task_index * INDEX_STRIDE + self._frames_so_far

        # ---- tabular columns ----
        cols, arrays, stats = {}, {}, {}
        for k in self.vector_keys:
            a = np.stack(self._buf["vectors"][k]).astype(np.float32)  # (n, d)
            arrays[k] = a
            cols[k] = pa.FixedSizeListArray.from_arrays(pa.array(a.reshape(-1), type=pa.float32()), a.shape[1])
            stats[k] = _stats_vec(a)
        frame_index = np.arange(n, dtype=np.int64)
        episode_index = np.full(n, ee, dtype=np.int64)
        index = (idx_base + np.arange(n)).astype(np.int64)
        task_index = np.full(n, self.task_index, dtype=np.int64)
        timestamp = (frame_index / self.fps).astype(np.float32)
        cols["timestamp"] = pa.array(timestamp, type=pa.float32())
        cols["frame_index"] = pa.array(frame_index, type=pa.int64())
        cols["episode_index"] = pa.array(episode_index, type=pa.int64())
        cols["index"] = pa.array(index, type=pa.int64())
        cols["task_index"] = pa.array(task_index, type=pa.int64())
        stats["timestamp"] = _stats_scalar(timestamp)
        stats["frame_index"] = _stats_scalar(frame_index)
        stats["episode_index"] = _stats_scalar(episode_index)
        stats["index"] = _stats_scalar(index)
        stats["task_index"] = _stats_scalar(task_index)

        # ---- parquet schema (+ embedded huggingface metadata) ----
        fields, hf = [], {}
        for k in self.vector_keys:
            fields.append(pa.field(k, pa.list_(pa.float32(), self.features[k]["shape"][0])))
            hf[k] = _hf_type("float32", self.features[k]["shape"])
        for k in self.scalar_float_keys:
            fields.append(pa.field(k, pa.float32())); hf[k] = _hf_type("float32", [1])
        for k in self.scalar_int_keys:
            fields.append(pa.field(k, pa.int64())); hf[k] = _hf_type("int64", [1])
        schema = pa.schema(fields, metadata={b"huggingface": json.dumps({"info": {"features": hf}}).encode()})
        table = pa.table({f.name: cols[f.name] for f in fields}, schema=schema)
        parquet_out = os.path.join(self.root, "data", self._tt, f"episode_{ee:08d}.parquet")

        # Stage every artifact first. The parquet is renamed last and is the completion marker used
        # by resume/rebuild, so an interrupted encoder cannot create a loadable partial episode.
        ann = dict(annotation or {})
        ann.setdefault("task_name", self.task_name)
        ann.setdefault("episode_index", ee)
        ann.setdefault("meta_data", {})
        ann["meta_data"].update({"length": int(n), "valid_range": [0, int(n)], "success": bool(success)})
        annotation_out = os.path.join(self.root, "annotations", self._tt, f"episode_{ee:08d}.json")
        staged, committed = [], []
        try:
            fd, parquet_tmp = tempfile.mkstemp(prefix=f".episode_{ee:08d}.", suffix=".parquet",
                                               dir=os.path.dirname(parquet_out))
            os.close(fd)
            staged.append(parquet_tmp)
            pq.write_table(table, parquet_tmp)

            video_pairs = []
            for vk in self.video_keys:
                frames = np.stack(self._buf["images"][vk])
                out = os.path.join(self.root, "videos", self._tt, vk, f"episode_{ee:08d}.mp4")
                fd, tmp = tempfile.mkstemp(prefix=f".episode_{ee:08d}.", suffix=".mp4",
                                           dir=os.path.dirname(out))
                os.close(fd)
                os.unlink(tmp)  # the encoder creates its output path
                staged.append(tmp)
                images_to_video(frames, tmp, fps=self.fps, is_rgb=True)
                if not os.path.isfile(tmp) or os.path.getsize(tmp) == 0:
                    raise RuntimeError(f"video encoder produced no output for {vk}")
                stats[vk] = _stats_image(self._buf["images"][vk])
                video_pairs.append((tmp, out))

            fd, annotation_tmp = tempfile.mkstemp(prefix=f".episode_{ee:08d}.", suffix=".json",
                                                  dir=os.path.dirname(annotation_out), text=True)
            with os.fdopen(fd, "w") as fh:
                json.dump(ann, fh, indent=2)
            staged.append(annotation_tmp)

            for tmp, out in video_pairs:
                os.replace(tmp, out)
                committed.append(out)
            os.replace(annotation_tmp, annotation_out)
            committed.append(annotation_out)
            os.replace(parquet_tmp, parquet_out)  # completion marker: commit last
            committed.append(parquet_out)
        except BaseException:
            for path in staged:
                try:
                    if os.path.exists(path):
                        os.unlink(path)
                except OSError:
                    pass
            if parquet_out not in committed:
                for path in committed:
                    try:
                        os.unlink(path)
                    except OSError:
                        pass
            self._reset_buf()
            raise

        # ---- meta slices ----
        ep_line = {"episode_index": ee, "tasks": [task], "length": int(n), "success": bool(success)}
        if extra_ep:
            ep_line.update(extra_ep)
        self._ep_lines.append(ep_line)
        self._stats_lines.append({"episode_index": ee, "stats": stats})
        self._task_strings[self.task_index] = task   # canonical instruction for this task

        self._local += 1
        self._frames_so_far += n
        self._reset_buf()
        return ee

    # ------------------------------------------------------------------ finalize (per job)
    def close(self):
        parts = os.path.join(self.root, "meta", "_parts")
        with open(os.path.join(parts, f"{self._tt}.episodes.jsonl"), "w") as fh:
            for l in self._ep_lines:
                fh.write(json.dumps(l) + "\n")
        with open(os.path.join(parts, f"{self._tt}.episodes_stats.jsonl"), "w") as fh:
            for l in self._stats_lines:
                fh.write(json.dumps(l) + "\n")
        info_slice = {
            "task_index": self.task_index,
            "task_name": self.task_name,
            "task_strings": self._task_strings,   # {task_index: canonical instruction}
            "n_episodes": len(self._ep_lines),
            "n_frames": int(sum(l["length"] for l in self._ep_lines)),
            "n_videos": len(self._ep_lines) * len(self.video_keys),
            "fps": self.fps,
            "robot_type": self.robot_type,
            "features": self.features,
            "chunks_size": self.chunks_size,
            "video_codec": self.video_codec,
        }
        with open(os.path.join(parts, f"{self._tt}.info.json"), "w") as fh:
            json.dump(info_slice, fh, indent=2)


def build_features(camera_feature_names, rgb_hw, state_dim, endpose_dim, task_state_dim, action_dim,
                   fps, video_codec="h264"):
    """Construct the v2.1 `features` dict for the DOMINO aloha-agilex schema."""
    H, W = rgb_hw
    feats = {}
    for name in camera_feature_names:
        feats[name] = {
            "dtype": "video", "shape": [H, W, 3], "names": ["height", "width", "channels"],
            "info": {"video.height": H, "video.width": W, "video.codec": video_codec,
                     "video.pix_fmt": "yuv420p", "video.is_depth_map": False,
                     "video.fps": float(fps), "video.channels": 3, "has_audio": False},
        }
    feats["observation.state"] = {"dtype": "float32", "shape": [state_dim], "names": None}
    feats["observation.endpose"] = {"dtype": "float32", "shape": [endpose_dim], "names": None}
    feats["observation.task_state"] = {"dtype": "float32", "shape": [task_state_dim], "names": None}
    feats["action"] = {"dtype": "float32", "shape": [action_dim], "names": None}
    feats["timestamp"] = {"dtype": "float32", "shape": [1], "names": None}
    feats["frame_index"] = {"dtype": "int64", "shape": [1], "names": None}
    feats["episode_index"] = {"dtype": "int64", "shape": [1], "names": None}
    feats["index"] = {"dtype": "int64", "shape": [1], "names": None}
    feats["task_index"] = {"dtype": "int64", "shape": [1], "names": None}
    return feats
